// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"context"
	"github.com/dysodeng/app/internal/application/file/decorator"
	"github.com/dysodeng/app/internal/application/file/event/handler"
	service3 "github.com/dysodeng/app/internal/application/file/service"
	service7 "github.com/dysodeng/app/internal/application/model/service"
	service2 "github.com/dysodeng/app/internal/application/passport/service"
	service5 "github.com/dysodeng/app/internal/application/workspace/service"
	"github.com/dysodeng/app/internal/di/event"
	"github.com/dysodeng/app/internal/di/modules"
	"github.com/dysodeng/app/internal/di/provider"
	service6 "github.com/dysodeng/app/internal/domain/model/service"
	"github.com/dysodeng/app/internal/domain/user/service"
	service4 "github.com/dysodeng/app/internal/domain/workspace/service"
	"github.com/dysodeng/app/internal/infrastructure/persistence/repository/cache"
	"github.com/dysodeng/app/internal/infrastructure/persistence/repository/file"
	"github.com/dysodeng/app/internal/infrastructure/persistence/repository/model"
	"github.com/dysodeng/app/internal/infrastructure/persistence/repository/permission"
	"github.com/dysodeng/app/internal/infrastructure/persistence/repository/workspace"
	"github.com/dysodeng/app/internal/interfaces/grpc"
	service8 "github.com/dysodeng/app/internal/interfaces/grpc/service"
	"github.com/dysodeng/app/internal/interfaces/http"
	file2 "github.com/dysodeng/app/internal/interfaces/http/handler/file"
	model2 "github.com/dysodeng/app/internal/interfaces/http/handler/model"
	"github.com/dysodeng/app/internal/interfaces/http/handler/passport"
	workspace2 "github.com/dysodeng/app/internal/interfaces/http/handler/workspace"
	"github.com/dysodeng/app/internal/interfaces/websocket"
)

// Injectors from wire.go:

// InitApp 初始化应用程序
func InitApp(ctx context.Context) (*App, error) {
	config, err := provider.ProvideConfig()
	if err != nil {
		return nil, err
	}
	monitor, err := provider.ProvideMonitor(config)
	if err != nil {
		return nil, err
	}
	logger, err := provider.ProvideLogger(ctx, config)
	if err != nil {
		return nil, err
	}
	transactionManager, err := provider.ProvideDB(ctx, config)
	if err != nil {
		return nil, err
	}
	client, err := provider.ProvideRedis(config)
	if err != nil {
		return nil, err
	}
	mq, err := provider.ProvideMessageQueue(config)
	if err != nil {
		return nil, err
	}
	storage, err := provider.ProvideStorage(config)
	if err != nil {
		return nil, err
	}
	userRepository := cache.NewCachedUserRepository(transactionManager)
	userDomainService := service.NewUserDomainService(userRepository)
	adminRepository := permission.NewAdminRepository(transactionManager)
	passportApplicationService := service2.NewPassportApplicationService(userRepository, userDomainService, adminRepository)
	passportHandler := passport.NewPassportHandler(passportApplicationService)
	fileRepository := file.NewFileRepository(transactionManager)
	uploaderRepository := file.NewUploaderRepository(transactionManager)
	fileStorage := provider.ProvideFileStoragePort(storage)
	filePolicy := provider.ProvideFilePolicyPort(config)
	uploaderDomainService := decorator.NewUploaderDomainServiceWithTracing(fileRepository, uploaderRepository, fileStorage, filePolicy)
	bus := provider.ProvideEventBus(mq)
	eventPublisher := provider.ProvideEventPublisherPort(bus)
	portTransactionManager := provider.ProvideTransactionManagerPort(transactionManager)
	uploaderApplicationService := service3.NewUploaderApplicationService(uploaderDomainService, eventPublisher, portTransactionManager, fileRepository, uploaderRepository, fileStorage)
	uploaderHandler := file2.NewUploaderHandler(uploaderApplicationService)
	repository := workspace.NewWorkspaceRepository(transactionManager)
	serviceService := service4.NewWorkspaceDomainService(repository)
	service9 := service5.NewWorkspaceApplicationService(serviceService)
	workspaceHandler := workspace2.NewWorkspaceHandler(service9)
	providerRepository := model.NewProviderRepository(transactionManager)
	instanceRepositoryConfig := modules.ProvideInstanceRepositoryConfig(config)
	instanceRepository := model.NewInstanceRepository(transactionManager, instanceRepositoryConfig)
	service10 := service6.NewModelDomainService(providerRepository, instanceRepository)
	service11 := service7.NewModelApplicationService(service10)
	providerHandler := model2.NewProviderHandler(service11)
	instanceHandler := model2.NewInstanceHandler(service11)
	handlerRegistry := http.NewHandlerRegistry(passportHandler, uploaderHandler, workspaceHandler, providerHandler, instanceHandler)
	textMessageHandler := websocket.NewTextMessageHandler()
	binaryMessageHandler := websocket.NewBinaryMessageHandler()
	webSocket := websocket.NewWebSocket(textMessageHandler, binaryMessageHandler)
	fileUploadedHandler := handler.NewFileUploadedHandler()
	eventHandlerRegistry := event.NewHandlerRegistry(fileUploadedHandler)
	fileDomainService := decorator.NewFileDomainServiceWithTracing(fileRepository)
	fileApplicationService := service3.NewFileApplicationService(fileDomainService)
	fileService := service8.NewFileService(fileApplicationService)
	serviceRegistry := grpc.NewServiceRegistry(fileService)
	server := provider.ProvideHTTPServer(config, handlerRegistry)
	grpcServer := provider.ProvideGRPCServer(ctx, config, serviceRegistry)
	websocketServer := provider.ProvideWebSocketServer(config, webSocket)
	healthServer := provider.ProvideHealthServer(config)
	consumerService := provider.ProvideEventConsumerService(mq, logger)
	eventServer := provider.ProvideEventServer(config, consumerService, eventHandlerRegistry)
	app := NewApp(config, monitor, logger, transactionManager, client, mq, storage, handlerRegistry, webSocket, eventHandlerRegistry, serviceRegistry, server, grpcServer, websocketServer, healthServer, bus, consumerService, eventServer)
	return app, nil
}
